### ISSUE TITLE
Fix broken task update

### ISSUE THREAD

**Issue by bhubr** [bhubr/react-time-tracker#40]
PUT to `/api/tasks/:id` fails (e.g. when marking a task as done).

```
trakt-back: [Nest] 39097   - 02/24/2020, 2:19:13 AM   [ExceptionsHandler] No entity column "timeboxes" was found. +277887ms
trakt-back: EntityColumnNotFound: No entity column "timeboxes" was found.
trakt-back:     at new EntityColumnNotFound (/Users/benoit/Code/react-time-tracker/packages/back/node_modules/typeorm/error/EntityColumnNotFound.js:10:28)
trakt-back:     at /Users/benoit/Code/react-time-tracker/packages/back/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:329:27
trakt-back:     at Array.forEach (<anonymous>)
trakt-back:     at UpdateQueryBuilder.createUpdateExpression (/Users/benoit/Code/react-time-tracker/packages/back/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:325:85)
trakt-back:     at UpdateQueryBuilder.getQuery (/Users/benoit/Code/react-time-tracker/packages/back/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:42:24)
trakt-back:     at UpdateQueryBuilder.QueryBuilder.getQueryAndParameters (/Users/benoit/Code/react-time-tracker/packages/back/node_modules/typeorm/query-builder/QueryBuilder.js:224:26)
trakt-back:     at UpdateQueryBuilder.<anonymous> (/Users/benoit/Code/react-time-tracker/packages/back/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:83:50)
trakt-back:     at step (/Users/benoit/Code/react-time-tracker/packages/back/node_modules/tslib/tslib.js:136:27)
trakt-back:     at Object.next (/Users/benoit/Code/react-time-tracker/packages/back/node_modules/tslib/tslib.js:117:57)
trakt-back:     at /Users/benoit/Code/react-time-tracker/packages/back/node_modules/tslib/tslib.js:110:75
trakt-back: PUT /api/tasks/31 500 22.447 ms - 52
```

This is apparently an issue with TypeORM's OneToMany associations. Gotta fix it with manual queries.

**Comment by bhubr** [comment]
<https://typeorm.io/#/update-query-builder>

**Comment by bhubr** [comment]
Finally wasn't due to TypeORM but to how I used it: https://github.com/typeorm/typeorm/issues/4477#issuecomment-590142742
